//! Help for the verbs that change the tracker
//!
//! Grouped the way `cli::dispatch` groups the same verbs, so adding one touches the
//! matching pair rather than a table nobody can find the right end of.

use super::VerbHelp;

pub(super) const VERBS: &[VerbHelp] = &[
    VerbHelp {
        verb: "new",
        tagline: "create a new issue (then edit its prose)",
        usage: "trck new <title> [options]",
        blurb: "Create an issue: write its markdown file from a prose template and add it to the index; prints the new path.",
        args: &[("title", "short title (also derives the slug)")],
        opts: &[
            ("--priority PRIORITY", "urgent, high, medium, low or lowest (default: medium)"),
            ("--points POINTS", "leaf weight for rollups (default 1)"),
            ("--parent PARENT", "id of the epic to nest this under"),
            ("--requires REQUIRES", "comma-separated ids this issue depends on (must be done first)"),
            ("--spec SPEC", "path to a spec/design doc"),
            ("--review-url REVIEW_URL", "where the output will be reviewed (absolute http(s) URL)"),
            ("--slug SLUG", "override the auto-derived filename slug"),
            ("--id ID", "use this id instead of generating one (for importing issues from another tracker, or restoring one)"),
        ],
        alias_of: "",
        example: "trck new \"Add CSV export\" --priority high --parent 4 --requires 5,6",
    },
    VerbHelp {
        verb: "mv",
        tagline: "move an issue to a status",
        usage: "trck mv <id> <status> [options]",
        blurb: "Move an issue to any of the four statuses.",
        args: &[("id", "issue id"), ("status", "backlog, in-progress, in-review or done")],
        opts: &[
            ("--resolution RESOLUTION", "why it closed without shipping (superseded, wontfix, duplicate); only valid when moving to a terminal status"),
            ("--review-url REVIEW_URL", "record a review URL as part of the move"),
        ],
        alias_of: "",
        example: "",
    },
    VerbHelp {
        verb: "start",
        tagline: "alias: move to in-progress",
        usage: "trck start <id>",
        blurb: "Alias: move an issue to in-progress. With no assignee field, this is how a tracker records a claim: from here the issue is out of ready/next, so nobody else is offered it, and `next` names it on its in-flight line instead.",
        args: &[("id", "issue id")],
        opts: &[],
        alias_of: "",
        example: "",
    },
    VerbHelp {
        verb: "review",
        tagline: "alias: move to in-review (and link a PR)",
        usage: "trck review <id> [url]",
        blurb: "Alias: move an issue to in-review and — given a URL — record it as the issue's pull request, in one step. An issue there stays out of ready/next (nothing to pick up), but still blocks whatever depends on it until the PR lands.",
        args: &[("id", "issue id"), ("url", "pull-request URL to link (optional)")],
        opts: &[("--review-url REVIEW_URL", "the same URL as a flag, for a caller that would rather be explicit")],
        alias_of: "",
        example: "trck review 7 https://github.com/o/r/pull/12",
    },
    VerbHelp {
        verb: "done",
        tagline: "alias: move to done",
        usage: "trck done <id> [options]",
        blurb: "Alias: move an issue to done.",
        args: &[("id", "issue id")],
        opts: &[("--resolution RESOLUTION", "why it closed without shipping (superseded, wontfix, duplicate); omit it when the work actually shipped")],
        alias_of: "",
        example: "",
    },
    VerbHelp {
        verb: "set",
        tagline: "edit metadata fields",
        usage: "trck set <id> [options]",
        blurb: "Edit an issue's metadata in place. Pass 'none' to clear parent/spec. Changing --slug renames the file; changing --title also rewrites the body's H1.",
        args: &[("id", "issue id")],
        opts: &[
            ("--priority PRIORITY", "urgent, high, medium, low or lowest"),
            ("--points POINTS", "leaf weight (error if the issue has children)"),
            ("--parent PARENT", "epic id, or 'none' to clear"),
            ("--spec SPEC", "path, or 'none' to clear"),
            ("--review-url REVIEW_URL", "review URL, or 'none' to clear"),
            ("--title TITLE", "new title (also rewrites the body's H1)"),
            ("--slug SLUG", "override the filename slug (renames the file)"),
            ("--field FIELD", "set a custom field (repeatable); empty value clears it"),
            ("--unset UNSET", "remove a custom field (repeatable)"),
            ("--auto", "clear a manual status override; let status derive from children"),
        ],
        alias_of: "",
        example: "",
    },
    VerbHelp {
        verb: "dep",
        tagline: "add/remove a dependency edge",
        usage: "trck dep <id> [options]",
        blurb: "Add or remove a dependency edge: make <id> depend on another issue (which must be done first).",
        args: &[("id", "issue id")],
        opts: &[("--add ADD", "id this issue should depend on"), ("--remove REMOVE", "id to remove from this issue's dependencies")],
        alias_of: "",
        example: "trck dep 7 --add 5    # 7 now waits on 5",
    },
    VerbHelp {
        verb: "label",
        tagline: "add/remove labels on an issue",
        usage: "trck label <id> [options]",
        blurb: "Add or remove free-text labels on an issue. Labels are a flat, unordered set; both flags are repeatable.",
        args: &[("id", "issue id")],
        opts: &[("--add ADD", "label to add (repeatable)"), ("--remove REMOVE", "label to remove (repeatable)")],
        alias_of: "",
        example: "trck label 7 --add backend --add urgent --remove stale",
    },
];
