from __future__ import annotations
from .config import is_terminal, status_names
from .constants import date_slice
from .graph import Graph, load_graph
from .index import Ctx, get_id, rel_link
from .render import label_tag, priority_rank, review_tag

# --------------------------------------------------------------------------- #
# SUMMARY.md generation
# --------------------------------------------------------------------------- #
def leaf_rollup(g: Graph, row, seen=frozenset()) -> tuple[int, int, int, int]:
    """Aggregate (done_points, total_points, done_count, total_count) over the leaf
    descendants of `row`, deriving children and terminal-ness from `g`. A leaf's weight
    defaults to 1; a node's weight is the sum of its leaves. Cycle-guarded so a
    malformed (mid-edit) index can't spin forever."""
    if row.id in seen:
        return 0, 0, 0, 0
    kids = g.children_of(row)
    if not kids:  # leaf
        pts = row.points
        done = g.is_terminal(row)
        return pts if done else 0, pts, 1 if done else 0, 1
    seen = seen | {row.id}
    pdone = ptotal = ndone = ntotal = 0
    for k in kids:
        a, b, c, d = leaf_rollup(g, k, seen)
        pdone += a
        ptotal += b
        ndone += c
        ntotal += d
    return pdone, ptotal, ndone, ntotal


def progress_pct(g: Graph, row) -> str:
    """A ` NN%` points-weighted completion suffix for parent rows (issues with children),
    derived from leaf descendants via `leaf_rollup` — the same number `summary` reports.
    Empty for leaves, which have nothing to roll up; `ptotal == 0` falls back to `0%`."""
    if g.is_leaf(row):
        return ""
    pdone, ptotal, _, _ = leaf_rollup(g, row)
    pct = round(100 * pdone / ptotal) if ptotal else 0
    return f" {pct}%"


def generate_summary(ctx: Ctx, rows: list | None = None) -> str:
    """Render the rollup. Pass `rows` to render from an in-memory set instead of
    re-reading index.jsonl — the merge driver needs this, because during a merge
    the working-tree index is not yet the merged result and reading it would
    produce a confidently wrong rollup."""
    g = Graph(ctx.cfg, rows) if rows is not None else load_graph(ctx)
    rows = g.rows
    names = status_names(ctx.cfg)

    counts = {n: 0 for n in names}
    for r in rows:
        counts[r.status] = counts.get(r.status, 0) + 1
    total = len(rows)

    out = [
        "<!-- GENERATED by `trck summary` — do not edit. -->",
        "# Issues Summary",
        "",
        "## Counts",
        "",
        "| State | Count |", "|---|---:|",
        *[f"| {n} | {counts[n]} |" for n in names],
        f"| **total** | **{total}** |",
        ""
    ]

    parents = sorted([r for r in rows if not g.is_leaf(r)], key=get_id)
    if parents:
        out.append("## Hierarchies")
        out.append("")
        for parent in parents:
            kids = g.children_of(parent)  # id-sorted
            pdone, ptotal, ndone, ntotal = leaf_rollup(g, parent)
            pct = round(100 * pdone / ptotal) if ptotal else 0
            out.append(
                f"### [#{parent.id} {parent.title}]({rel_link(parent)}) — "
                f"{pct}% ({pdone}/{ptotal} pts · {ndone}/{ntotal} done) · "
                f"_{parent.priority}_ · {parent.status}"
            )
            if parent.spec:
                out.append(f"Spec: [`{parent.spec}`](../{parent.spec})")
            if parent.review_url:
                out.append(f"Review: [{parent.review_url}]({parent.review_url})")
            if kids:
                out.append("")
                for k in kids:
                    box = "x" if g.is_terminal(k) else " "
                    tail = "" if g.is_terminal(k) else f" _({k.status})_"
                    out.append(f"- [{box}] [#{k.id} {k.title}]"
                               f"({rel_link(k)}){label_tag(k)}{tail}{review_tag(k)}")
            out.append("")

    def standalone(s: str):
        issues = [t for t in rows if t.status == s and g.is_leaf(t) and t.parent is None]
        return sorted(issues, key=lambda x: (priority_rank(ctx.cfg, x.priority), x.id))

    for status in names:
        items = standalone(status)
        out.append(f"## {status.capitalize()}")
        out.append("")
        if not items:
            out.append("_none_")
        for r in items:
            extra = ""
            if r.resolution:
                extra += f" · _{r.resolution}_"
            if is_terminal(ctx.cfg, status) and r.closed:
                extra += f" (closed {date_slice(r.closed)})"
            out.append(f"- [#{r.id} {r.title}]({rel_link(r)}) — "
                       f"_{r.priority}_{label_tag(r)}{extra}{review_tag(r)}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def write_summary(ctx: Ctx, rows: list | None = None) -> None:
    (ctx.dir / "SUMMARY.md").write_text(generate_summary(ctx, rows))


