//! `SUMMARY.md` — the generated rollup every mutation rewrites.
//!
//! Byte-identical to the Python engine's output, because it is a committed file: a
//! difference is a diff in someone's working tree, not a cosmetic detail. It is
//! generated, never hand-edited, which is what lets the tracker be text and still not
//! drift.
//!
//! Three sections: the counts table, one block per parent with its rollup and children,
//! and one block per status listing the *standalone* leaves — issues with no parent, so
//! nothing appears twice.

use crate::config::{self, is_terminal};
use crate::graph::{Graph, priority_rank};
use crate::issue::Issue;
use std::fmt::Write as _;

/// `items/<id>-<slug>.md`, the link target used throughout.
pub(crate) fn rel_link(row: &Issue) -> String {
    format!("items/{}", filename(row))
}

/// An issue's body filename. The path encodes id and slug only — status lives in the
/// index alone, so a move never touches the filesystem.
pub(crate) fn filename(row: &Issue) -> String {
    format!("{}-{}.md", row.id, row.slug)
}

/// ` [a b]` for a labelled issue, empty otherwise.
fn label_tag(row: &Issue) -> String {
    if row.labels.is_empty() { String::new() } else { format!(" [{}]", row.labels.join(" ")) }
}

/// ` · [review](url)` when an issue records where its output is being judged.
fn review_tag(row: &Issue) -> String {
    row.review_url.as_ref().map_or_else(String::new, |u| format!(" · [review]({u})"))
}

/// The date part of a timestamp. Summary rows show the day, not the second.
fn date_slice(ts: &str) -> &str {
    ts.get(..10).unwrap_or(ts)
}

/// Percentage, rounding half away from zero as Python's `round` does not — but both
/// agree on every value reachable here, since points are non-negative.
fn pct(done: i64, total: i64) -> i64 {
    if total == 0 { 0 } else { (200 * done + total) / (2 * total) }
}

/// Capitalise the first character, as Python's `str.capitalize` does for these names.
fn capitalise(s: &str) -> String {
    let mut chars = s.chars();
    chars.next().map_or_else(String::new, |c| c.to_uppercase().collect::<String>() + chars.as_str())
}

/// The counts table: one row per status, whether or not anything is in it. The table is
/// the vocabulary, not a histogram of what happens to exist today.
fn counts_section(g: &Graph) -> Vec<String> {
    let mut out: Vec<String> = vec![
        "<!-- GENERATED by `trck summary` — do not edit. -->".into(),
        "# Issues Summary".into(),
        String::new(),
        "## Counts".into(),
        String::new(),
        "| State | Count |".into(),
        "|---|---:|".into(),
    ];
    for name in config::STATUSES {
        let n = g.rows.iter().filter(|r| r.status == *name).count();
        out.push(format!("| {name} | {n} |"));
    }
    out.push(format!("| **total** | **{}** |", g.rows.len()));
    out.push(String::new());
    out
}

/// One block per parent: its rollup, its spec and review links, and its children.
fn hierarchies_section(g: &Graph) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut parents: Vec<&Issue> = g.rows.iter().filter(|r| !g.is_leaf(&r.id)).collect();
    parents.sort_by(|a, b| a.id.cmp(&b.id));
    if !parents.is_empty() {
        out.push("## Hierarchies".into());
        out.push(String::new());
        for parent in parents {
            let (pdone, ptotal, ndone, ntotal) = g.leaf_rollup(&parent.id);
            out.push(format!(
                "### [#{} {}]({}) — {}% ({pdone}/{ptotal} pts · {ndone}/{ntotal} done) · _{}_ · {}",
                parent.id,
                parent.title,
                rel_link(parent),
                pct(pdone, ptotal),
                parent.priority,
                parent.status
            ));
            if let Some(spec) = &parent.spec {
                out.push(format!("Spec: [`{spec}`](../{spec})"));
            }
            if let Some(url) = &parent.review_url {
                out.push(format!("Review: [{url}]({url})"));
            }
            let kids = g.children_of(&parent.id);
            if !kids.is_empty() {
                out.push(String::new());
                for kid in kids {
                    let Some(k) = g.get(kid) else { continue };
                    let done = is_terminal(&k.status);
                    out.push(format!(
                        "- [{}] [#{} {}]({}){}{}{}",
                        if done { "x" } else { " " },
                        k.id,
                        k.title,
                        rel_link(k),
                        label_tag(k),
                        if done { String::new() } else { format!(" _({})_", k.status) },
                        review_tag(k),
                    ));
                }
            }
            out.push(String::new());
        }
    }
    out
}

/// One block per status listing the *standalone* leaves. Parented issues appear under
/// their parent above, so listing them again would double-count the whole tracker.
fn status_sections(g: &Graph) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for status in config::STATUSES {
        let mut items: Vec<&Issue> = g.rows.iter().filter(|r| r.status == *status && g.is_leaf(&r.id) && r.parent.is_none()).collect();
        items.sort_by(|a, b| priority_rank(&a.priority).cmp(&priority_rank(&b.priority)).then(a.id.cmp(&b.id)));
        out.push(format!("## {}", capitalise(status)));
        out.push(String::new());
        if items.is_empty() {
            out.push("_none_".into());
        }
        for r in items {
            let mut extra = String::new();
            if let Some(res) = &r.resolution {
                let _ = write!(extra, " · _{res}_");
            }
            if is_terminal(status)
                && let Some(closed) = &r.closed
            {
                let _ = write!(extra, " (closed {})", date_slice(closed));
            }
            out.push(format!("- [#{} {}]({}) — _{}_{}{}{}", r.id, r.title, rel_link(r), r.priority, label_tag(r), extra, review_tag(r)));
        }
        out.push(String::new());
    }
    out
}

/// Render the rollup for a loaded graph.
pub(crate) fn generate_summary(g: &Graph) -> String {
    let mut out = counts_section(g);
    out.extend(hierarchies_section(g));
    out.extend(status_sections(g));
    let mut text = out.join("\n");
    while text.ends_with(char::is_whitespace) {
        text.pop();
    }
    text.push('\n');
    text
}

#[cfg(test)]
mod tests {
    // Tests assert; that is their job. The crate denies unwrap/expect/panic because a
    // malformed tracker must produce a diagnostic rather than a stack trace, but a test
    // that cannot panic cannot fail.
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;
    use crate::index::parse_index;
    use std::path::Path;

    fn graph_of(text: &str) -> Graph {
        Graph::new(parse_index(text, "index.jsonl").expect("parses"))
    }

    const ONE: &str = r#"{"id": "aaaaaaa", "slug": "a", "title": "Alpha", "status": "backlog", "priority": "high"}"#;

    #[test]
    fn the_counts_table_lists_every_status_even_at_zero() {
        // A status with nothing in it still gets a row: the table is the vocabulary,
        // not a histogram of what happens to exist today.
        let s = generate_summary(&graph_of(ONE));
        for name in config::STATUSES {
            assert!(s.contains(&format!("| {name} | ")), "missing {name}:\n{s}");
        }
        assert!(s.contains("| **total** | **1** |"), "{s}");
    }

    #[test]
    fn an_empty_status_section_says_none() {
        let s = generate_summary(&graph_of(ONE));
        assert!(s.contains("## Done\n\n_none_"), "{s}");
    }

    #[test]
    fn a_standalone_leaf_is_listed_once_under_its_status() {
        let s = generate_summary(&graph_of(ONE));
        assert_eq!(s.matches("#aaaaaaa").count(), 1, "{s}");
        assert!(s.contains("- [#aaaaaaa Alpha](items/aaaaaaa-a.md) — _high_"), "{s}");
    }

    #[test]
    fn a_parented_issue_appears_under_its_parent_not_in_the_status_list() {
        // Otherwise every child is counted twice by anyone reading the file.
        let text = format!("{ONE}\n{}\n", r#"{"id": "bbbbbbb", "slug": "b", "title": "Beta", "status": "backlog", "priority": "low", "parent": "aaaaaaa"}"#);
        let s = generate_summary(&graph_of(&text));
        assert!(s.contains("### [#aaaaaaa Alpha]"), "{s}");
        assert!(s.contains("- [ ] [#bbbbbbb Beta](items/bbbbbbb-b.md)"), "{s}");
        // Alpha is a parent now, so it is not a standalone leaf either.
        assert!(!s.contains("- [#bbbbbbb"), "{s}");
        assert!(!s.contains("- [#aaaaaaa"), "{s}");
    }

    #[test]
    fn a_done_child_is_ticked_and_drops_its_status_note() {
        let text = format!(
            "{ONE}\n{}\n",
            r#"{"id": "bbbbbbb", "slug": "b", "title": "Beta", "status": "done", "priority": "low", "parent": "aaaaaaa", "labels": ["x"]}"#
        );
        let s = generate_summary(&graph_of(&text));
        assert!(s.contains("- [x] [#bbbbbbb Beta](items/bbbbbbb-b.md) [x]\n"), "{s}");
    }

    #[test]
    fn standalone_issues_sort_by_priority_then_id() {
        let row = |id: &str, p: &str| format!(r#"{{"id": "{id}", "slug": "s", "title": "T", "status": "backlog", "priority": "{p}"}}"#);
        let text = format!("{}\n{}\n{}\n", row("ccccccc", "low"), row("aaaaaaa", "urgent"), row("bbbbbbb", "urgent"));
        let s = generate_summary(&graph_of(&text));
        let at = |id: &str| s.find(id).unwrap_or(usize::MAX);
        assert!(at("aaaaaaa") < at("bbbbbbb"));
        assert!(at("bbbbbbb") < at("ccccccc"));
    }

    #[test]
    fn a_closed_issue_shows_its_resolution_and_date() {
        let text = r#"{"id": "aaaaaaa", "slug": "a", "title": "Alpha", "status": "done", "priority": "high", "resolution": "wontfix", "closed": "2026-01-02T03:04:05Z"}"#;
        let s = generate_summary(&graph_of(text));
        assert!(s.contains("_wontfix_ (closed 2026-01-02)"), "{s}");
    }

    /// Regenerate this repo's committed `SUMMARY.md` and require the bytes back.
    ///
    /// It is a generated, committed file: a byte difference is a diff in someone's
    /// working tree. And it exercises what a hand-written case cannot — 195 real issues
    /// with real epics, labels, review links, resolutions and unicode titles.
    #[test]
    fn the_repos_own_summary_regenerates_byte_for_byte() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let mut checked = 0;
        for rel in ["issues", "examples/action-game"] {
            let dir = root.join(rel);
            let (Ok(index), Ok(want)) = (std::fs::read_to_string(dir.join("index.jsonl")), std::fs::read_to_string(dir.join("SUMMARY.md"))) else {
                continue; // a consumer of this crate need not have the tracker
            };
            let got = generate_summary(&graph_of(&index));
            assert_eq!(got, want, "{rel}/SUMMARY.md did not regenerate identically");
            checked += 1;
        }
        assert!(checked > 0, "no committed summary found to check");
    }
}
